### PR TITLE
Rewrite

### PR DESCRIPTION
**Pull request by tokenrove**
It's no longer useful to have all the PRNGs exposed from the NIF, and TLS as a (non)synchronization mechanism won.

---

This change is [Reviewable](https://reviewable.io/reviews/tokenrove/granderl/1)

### CODE REVIEW

**Comment by causal-agent** [comment]
Review status: 0 of 19 files reviewed at latest revision, 6 unresolved discussions.

---

_[.travis.yml, line 16 [r2]](https://reviewable.io:443/reviews/tokenrove/granderl/1#-KMVNHBP1uln5LJnbn5W:-KMVNHBP1uln5LJnbn5X:-725695001) ([raw file](https://github.com/tokenrove/granderl/blob/7da0ca0dd4f993f537dbdcd92289c495791e3a4b/.travis.yml#L16)):_

> ``` YAML
>   - make
>   - make install
>   - export PATH=$PATH:$TRAVIS_BUILD_DIR/bin
> ```

Nitpick but want to try Reviewable: isn't it unnecessary to write `export PATH` since `PATH` is already an exported variable?

---

_[.travis.yml, line 32 [r2]](https://reviewable.io:443/reviews/tokenrove/granderl/1#-KMVOdq20mpk-ri4QqeL:-KMVOdq20mpk-ri4QqeM:-1623433549) ([raw file](https://github.com/tokenrove/granderl/blob/7da0ca0dd4f993f537dbdcd92289c495791e3a4b/.travis.yml#L32)):_

> ``` YAML
>       - gcc-5
>       - libgsl0-dev
>       - perf
> ```

Excuse you.

---

_[bench.sh, line 3 [r2]](https://reviewable.io:443/reviews/tokenrove/granderl/1#-KMVOpX21GcRPKnoetkp:-KMVOpX21GcRPKnoetkq:-81781011) ([raw file](https://github.com/tokenrove/granderl/blob/7da0ca0dd4f993f537dbdcd92289c495791e3a4b/bench.sh#L3)):_

> ``` Shell
> #!/usr/bin/env bash
> #
> # Evaluate which function is fastest on this machine right now, and
> ```

And what?

---

_[dieharder.sh, line 3 [r2]](https://reviewable.io:443/reviews/tokenrove/granderl/1#-KMVPAHmMtF8P_3oLMpO:-KMVPAHmMtF8P_3oLMpP:-81781011) ([raw file](https://github.com/tokenrove/granderl/blob/7da0ca0dd4f993f537dbdcd92289c495791e3a4b/dieharder.sh#L3)):_

> ``` Shell
> #!/usr/bin/env bash
> #
> # Evaluate which function is fastest on this machine right now, and
> ```

And what?

---

_[c_src/granderl.c, line 11 [r2]](https://reviewable.io:443/reviews/tokenrove/granderl/1#-KMVQMYtY0Q-F68iTYT-:-KMVQMYuwL3JLezaQd34:-2113183879) ([raw file](https://github.com/tokenrove/granderl/blob/7da0ca0dd4f993f537dbdcd92289c495791e3a4b/c_src/granderl.c#L11)):_

> ``` C
> 
> static int upgrade(ErlNifEnv* env __attribute__((unused)),
>                    void ** priv __attribute__((unused)),
> ```

BTW you put a space there

---

_[c_src/rdtsc.h, line 8 [r2]](https://reviewable.io:443/reviews/tokenrove/granderl/1#-KMVSkhhikyPvHWmuVFT:-KMVSkhhikyPvHWmuVFU:-467760017) ([raw file](https://github.com/tokenrove/granderl/blob/7da0ca0dd4f993f537dbdcd92289c495791e3a4b/c_src/rdtsc.h#L8)):_

> ``` objc
> inline void rdtsc(uint64_t *t, uint64_t *u)
> {
>     __asm__ __volatile__ ("rdtsc" : "=a" (*t), "=d" (*u));
> ```

Inconsistent with `asm volatile` in `rdrand.h`.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/tokenrove/granderl/1)_

**Comment by causal-agent** [comment]
Reviewed 19 of 19 files at r2.
Review status: all files reviewed at latest revision, 4 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/tokenrove/granderl/1)_

**Comment by tokenrove** [comment]
@programble I believe my changes address your comments.

---

Review status: 14 of 19 files reviewed at latest revision, 4 unresolved discussions.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/tokenrove/granderl/1#-:-KMVXfTmz_YbnNEqz0uS:-265244263)_

**Comment by causal-agent** [comment]
Reviewed 5 of 5 files at r3.
Review status: all files reviewed at latest revision, all discussions resolved.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/tokenrove/granderl/1)_

**Comment by causal-agent** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, all discussions resolved, some commit checks pending.

---

_Comments from [Reviewable](https://reviewable.io:443/reviews/tokenrove/granderl/1#-:-KMVZDHD8TQoCy3jyZvl:1417088721)_

**Pull request merged**
